from random import *
users = range(1, 21)
print(type(users))
users = list(users)
print(type(users))
print(users)
shuffle(users)
print(users)
winners = sample(users, 4)
print(winners)
print("-- 담청자 발표 --")
print("치킨 당첨자 : "+ str(winners[3]))
print("커피 당첨자 : " + str(winners[:3]))
print("-- 축하합니다 --")